
#Anne Starley  
**Essay Questions** ADA Developer's Academy Application  
_________________________________________________  
####1. *Why are you interested in programming? What have you done to expose yourself to programming so far?*  
I am a graduate of Utah State University where I studied physics with a medical emphasis. I love learning. I love working hard on challenging and rewarding projects and doing a job well. My original plan was to continue my education and earn a master’s degree in biomedical engineering. However, when the time came to start applications for this step, I did not feel that it was right.  
After I came to this conclusion, I began to explore other options. I shadowed physician’s assistants, dentists, doctors, and mechanical engineers. I interviewed pharmacists and biomedical engineers but I never felt like I had found my niche.  
About a year ago, I talked to a friend who studied computer science and now works as a web developer. He told me that, although his studies had been challenging, the work was stimulating and rewarding. My interest was piqued! In the meantime, I took a job with Amazon and continued to search for my passion project, Networking events, research, and soul-searching painted a picture with two key components: One, many of the companies (and teams within those companies) that I very much wanted to work with are looking for software engineers. Two, a multitude of creative, rousing opportunities for coders is available.   
The final push came at Xbox’s Girl Geek Dinner. The event highlighted women who worked successfully in the tech industry. The speakers were impressive. The work they did was inventive and exciting. And the tech they present was out of this world. I was hooked. Or better, I was enthralled. I decided to look into mastering the valuable skillset of coding.  
I spoke to multiple software engineers about their daily activities and the pathways that had led to their particular careers. I loved it! I know not every coder works for Xbox creating new games and worlds and stories within those games but I also am sure there is plenty of opportunity for original and interesting work that I would love to be a part of within this field.  
I have had some experience with coding. While at Utah State University, I took Computer Methods in Physics. I also audited a beginners’ computer science class that taught C++ to learn the basics of coding language for my work with the Utah State University Material Physics Group.  
My work with the Material Physics Group afforded me the opportunity to work with programs such as Mathcad, Maple, and Matlab, all of which had languages of their own, which I enjoyed learning.  I also worked extensively with PuTTY to find the gap between the Highest Occupied Molecular Orbit and the Lowest Unoccupied Molecular Orbit in various liquid materials. This work demanded that I write and run many “jobs” through the Utah State University Gaussian System using PuTTY as my program.  

####2. *If you are accepted into our program, where do you see your career in 5 years?*  

The opportunities that the Northwest, particularly Seattle, presents to software engineers seems like it might be endless. I would love to work as a coder for an exciting company doing cutting-edge work; I am currently drawn to Snapchat, Inc., Microsoft, and Amazon (especially their IMDB or Goodreads teams). I would also be eager to work for a new, innovative start-up company. I definitely hope to be working in the Northwest, creating and blazing onwards.  
Furthermore, I intend to be on my way to being an influential woman in the tech world. I’ll use the skills and experiences I have gained to encourage girls (my nieces are taking coding classes in elementary school!) and other women to pursue careers in a field that is classically largely represented by a certain narrow demographic and may not have a lot of female representation or may not have offered a great deal of encouragement to women in the past. The outreach event of Microsoft’s Xbox, especially the women of Xbox, helped me to decide to follow this course. I would love to do the same for others!  

####3. *After reading Ada's Vision, Mission and Inclusivity Statement, how will you contribute to Ada's vision for an inclusive and diverse community?*  
Although my gender is not the only thing that defines me, I would be in a somewhat unique position as a female in a predominantly male environment. It shouldn’t be this way and I would like to be a drop in the ocean of change in that regard.  
We live in an ever increasingly technical world and most people rely heavily on the internet, smart phones, apps, and on and on. I use technology constantly. I use it to get around, to track traffic, to communicate with my loved ones, to share and connect with friends, to express myself creatively, to entertain myself and others, and so much more. The coders of today are going to shape the next generation of programs. If we want tech products to appeal to and most correctly serve all of the population, the people working in the tech industry should be a better representation of the population (51 percent of the world’s population is female). Women, for the most part, think more like other women than men do. Women have a better idea of what other women will find entertaining. Women know what might be important to include in a certain app or program that men just might not consider. Moreover, presenting the same problem to people of different backgrounds and experience will produce a larger variety of creative results.  
I come from a much smaller town than Seattle and was raised in a family that doesn’t have a ton of technical experience (a lot of dentists actually). As a woman, born and raised outside of the fascinating technical world, I can offer a unique perspective, and I relish the idea of working with others who have different backgrounds and outlooks than my own. I enjoy connecting and working with others in a meaningful and creative way and see coding as a way to do so.  

####4. *Tell us about a time you made a mistake that you learned a lot from. If you encountered the situation again, what would you do differently?*  
This summer, I took an “organized” humanitarian trip to Haiti. I was seeking a way to simultaneously reach out to others and take an adventure outside my native lands. I joined a group that was working with an organization called Haiti Health Initiative. [HHI](http://haitihealthinitiative.org/ "Check out their webpage here!") is a wonderful organization, and I am happy to be involved with it. The group I was traveling with, however, was unprepared and disorganized. I should have seen this early on. In the end, the trip did accomplish many things, but it was less of a success than it could have been and a much bigger hassle than it should have been. I learned that, next time, a trip like that deserved a lot more research. Basically, I didn’t do my homework.  
The people who introduced me to the group were fun and exciting. The general layout of the trip and the projects it would entail sounded worthwhile and like something I could effectively contribute to. I heard the bare details and, a week later, signed up for the entire trip. Headstrong when it came to this trip, I ignored suggestions to conduct more research and talk to upper-level board members before I had committed.  
A myriad of things went wrong. To start off, there was confusion on who was responsible for the arrangements the trip required. The person who seemed to be in charge dropped out and was confused at the team’s consternation, as he thought someone else was heading that aspect of the trip. Meanwhile, the young woman put in charge in his stead desperately did not want to take on that role; she was studying for college finals and felt she hadn’t signed up for that particular role. It was confusing and rough start! As a result transportation, food, security, and other important details were not in place for our scheduled departure date. Finally the head of HHI stepped in, and with an expensive plane ticket change for everyone involved, the necessary arrangements were made and we headed out two weeks later.  
Our troubles did not stop there. The Health Care Workers, school children, school teachers, and others we were working with had prepared for our planned earlier arrival. Schedules had to be rearranged, and not all were able to interact with us according to the original plan. Money was argued over, and some money, along with other items, was misplaced. Overall, I did not leave feeling like I had dedicated my time and resources in the most positive way for me or the people I wanted to serve.  
That said, I would not unmake this imprudent decision or undo this hectic experience. I learned a lot about HHI and the good ways in which people are reaching out to each other across the world. I learned how much I loved accomplishing goals that benefitted not only myself but others as well. Living briefly in a new country where people mostly spoke a language I did not understand taught me about myself, and it was a great time for self-reflection. I met many wonderful and admirable people who enriched my life and with whom I hope to remain friends for a long time. In addition, I remain involved with HHI today (in a *much* more structured fashion), and my work with the organization brings me a lot of fulfillment and happiness and presents plenty of opportunities for learning and growth.  
Nevertheless, the next time I take a trip out of the country with a group, I will not jump in with such reckless abandon. I have learned the practicality of adequately researching an important undertaking before dedicating time, energy and money to it. I have also learned the value of getting information from multiple sources and not just, for example, from a very enthusiastic group of young people. I learned that lack of preparation can hurt not only you but affect other people who are depending on you. All in all, I am grateful for the experience and the lessons it taught me – especially for the way its failures and mishaps will guide my future endeavors.
